
package com.helger.peppol.lime.api.wstransfer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.7-b01 Generated
 * source version: 2.2
 */
@WebService (name = "Resource", targetNamespace = "http://www.w3.org/2009/02/ws-tra")
@SOAPBinding (parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso ({ com.helger.peppol.identifier.ObjectFactory.class,
               com.helger.peppol.lime.api.wstransfer.ObjectFactory.class })
public interface Resource
{

  /**
   * @param body
   * @return returns org.w3._2009._02.ws_tra.GetResponse
   */
  @WebMethod (operationName = "Get")
  @WebResult (name = "GetResponse", targetNamespace = "http://www.w3.org/2009/02/ws-tra", partName = "Body")
  @Action (input = "http://www.w3.org/2009/02/ws-tra/Get", output = "http://www.w3.org/2009/02/ws-tra/GetResponse")
  public GetResponse get (@WebParam (name = "Get",
                                     targetNamespace = "http://www.w3.org/2009/02/ws-tra",
                                     partName = "Body") Get body);

  /**
   * @param body
   * @return returns org.w3._2009._02.ws_tra.PutResponse
   */
  @WebMethod (operationName = "Put")
  @WebResult (name = "PutResponse", targetNamespace = "http://www.w3.org/2009/02/ws-tra", partName = "Body")
  @Action (input = "http://www.w3.org/2009/02/ws-tra/Put", output = "http://www.w3.org/2009/02/ws-tra/PutResponse")
  public PutResponse put (@WebParam (name = "Put",
                                     targetNamespace = "http://www.w3.org/2009/02/ws-tra",
                                     partName = "Body") Put body);

  /**
   * @param body
   * @return returns org.w3._2009._02.ws_tra.DeleteResponse
   */
  @WebMethod (operationName = "Delete")
  @WebResult (name = "DeleteResponse", targetNamespace = "http://www.w3.org/2009/02/ws-tra", partName = "Body")
  @Action (input = "http://www.w3.org/2009/02/ws-tra/Delete",
           output = "http://www.w3.org/2009/02/ws-tra/DeleteResponse")
  public DeleteResponse delete (@WebParam (name = "Delete",
                                           targetNamespace = "http://www.w3.org/2009/02/ws-tra",
                                           partName = "Body") Delete body);

  /**
   * @param body
   * @return returns org.w3._2009._02.ws_tra.CreateResponse
   * @throws FaultMessage
   */
  @WebMethod (operationName = "Create")
  @WebResult (name = "CreateResponse", targetNamespace = "http://www.w3.org/2009/02/ws-tra", partName = "Body")
  @Action (input = "http://www.w3.org/2009/02/ws-tra/Create",
           output = "http://www.w3.org/2009/02/ws-tra/CreateResponse")
  public CreateResponse create (@WebParam (name = "Create",
                                           targetNamespace = "http://www.w3.org/2009/02/ws-tra",
                                           partName = "Body") Create body);

}
